name: C/C++ CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          
      - name: Update packages and install Python
        run: |
          sudo -n apt-get update
          sudo -n apt-get upgrade -y

      - name: Build
        run: |
          make -j4

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: out/


